/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/brain.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Atrophic_Brain_Cube%20T2%20Flair%203DFile_300000stl'].geometry} material={nodes['Atrophic_Brain_Cube%20T2%20Flair%203DFile_300000stl'].material} position={[0, 0, -0.587]} scale={0.008} />
    </group>
  )
}

useGLTF.preload('/brain.glb')
